title: Haonan's Tech Blog
name: "Haonan's English HomePage"
author: Haonan Feng
twitter_username: HoracceF
baseurl: "/HCF-en"
description: Find My Way
profile_url: "http://www.horaccefeng.com"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
